export const excelFieldMap = {
  '集团编码': 'group_code',
  '集团名称': 'group_name',
  '归属节点': 'node_code',
  '节点名称': 'node_name',
  '归属区分': 'region_name',
  '集团产品编码': 'group_product_code',
  '集团用户名称': 'group_user_name',
  '集团产品账户ID': 'group_product_account_id',
  '付费方式': 'payment_method',
  '付费方式名称': 'payment_method_name',
  '产品编码': 'product_code',
  '产品名称': 'product_name',
  '产品大类': 'product_category',
  '开始时间': 'start_time',
  '结束时间': 'end_time',
  '状态时间': 'status_time',
  '产品状态': 'product_status',
  '产品状态名称': 'product_status_name',
  '集团是否打标': 'is_group_tagged',
  '集团级别': 'group_level',
  '集团行业类别1': 'industry_code_1',
  '集团行业类别名称1': 'industry_name_1',
  '集团行业类别2': 'industry_code_2',
  '集团行业类别名称2': 'industry_name_2',
  '客户经理工号': 'manager_job_no',
  '客户经理名称': 'manager_name',
  '总欠费': 'total_arrears',
  '创建时间': 'source_created_time',
  '上月状态': 'last_month_status',
  '上上月状态': 'two_months_ago_status',
  '专线带宽': 'bandwidth',
  '最近半年是否出账为0': 'is_zero_billing_recent_6m',
  '活动套餐': 'package_code',
  '活动套餐名称': 'package_name',
  '活动套餐资费': 'package_fee',
  '活动套餐生效时间': 'package_effective_time',
  '活动套餐失效时间': 'package_expire_time',
  'A端地址': 'a_end_address',
  'Z端地址': 'z_end_address'
};

export const excelHeaders = Object.keys(excelFieldMap);

export const editableFields = [
  'actual_monthly_fee',
  'actual_yearly_fee',
  'one_time_fee',
  'one_time_fee_name',
  'one_time_fee_billing_month',
  'contract_no',
  'contract_start_date',
  'contract_end_date',
  'renewal_status',
  'renewal_reminder_date',
  'customer_contact',
  'customer_phone',
  'operation_owner',
  'business_owner',
  'project_name',
  'ledger_status',
  'remark'
];
